"""empty message

Revision ID: 00d9e204615b
Revises: 27209684050f
Create Date: 2020-01-31 01:30:06.747993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d9e204615b'
down_revision = '27209684050f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(length=250), nullable=False),
    sa.Column('contact_info', sa.String(length=250), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_info')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_profile')
    # ### end Alembic commands ###
