"""empty message

Revision ID: 1e35699335bc
Revises: 788c93f93546
Create Date: 2020-02-01 18:39:56.968923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e35699335bc'
down_revision = '788c93f93546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('create_job_posting')
    op.drop_table('createjobposting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('createjobposting',
    sa.Column('job_title', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('job_description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('job_date', sa.DATE(), nullable=True),
    sa.Column('skills_needed', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('hours_expected', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('payment', mysql.VARCHAR(length=25), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('create_job_posting',
    sa.Column('job_title', mysql.VARCHAR(length=50), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
