"""empty message

Revision ID: 27209684050f
Revises: 11613b7c085f
Create Date: 2020-01-31 00:15:50.986995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27209684050f'
down_revision = '11613b7c085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer')
    # ### end Alembic commands ###
