"""empty message

Revision ID: 314c4ab28e60
Revises: b8c17523a087
Create Date: 2020-02-05 01:02:45.966317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '314c4ab28e60'
down_revision = 'b8c17523a087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('company', sa.Column('company_description', sa.String(length=120), nullable=False))
    op.add_column('company', sa.Column('re_password', sa.String(length=120), nullable=False))
    op.drop_column('company', 'full_name')
    op.add_column('user', sa.Column('re_password', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('skills', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('user', 'username')
    op.drop_column('user', 'skills')
    op.drop_column('user', 're_password')
    op.add_column('company', sa.Column('full_name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('company', 're_password')
    op.drop_column('company', 'company_description')
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
