"""empty message

Revision ID: 4d8c3041b8f6
Revises: 232295cddbb1
Create Date: 2020-02-13 03:48:32.221516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8c3041b8f6'
down_revision = '232295cddbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hours_expected', table_name='job_posting')
    op.drop_index('job_date', table_name='job_posting')
    op.drop_index('job_description', table_name='job_posting')
    op.drop_index('job_title', table_name='job_posting')
    op.drop_index('payment', table_name='job_posting')
    op.drop_index('skills_needed', table_name='job_posting')
    op.drop_index('zip_code', table_name='job_posting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('zip_code', 'job_posting', ['zip_code'], unique=True)
    op.create_index('skills_needed', 'job_posting', ['skills_needed'], unique=True)
    op.create_index('payment', 'job_posting', ['payment'], unique=True)
    op.create_index('job_title', 'job_posting', ['job_title'], unique=True)
    op.create_index('job_description', 'job_posting', ['job_description'], unique=True)
    op.create_index('job_date', 'job_posting', ['job_date'], unique=True)
    op.create_index('hours_expected', 'job_posting', ['hours_expected'], unique=True)
    # ### end Alembic commands ###
