"""empty message

Revision ID: 5df9d0368e07
Revises: 314c4ab28e60
Create Date: 2020-02-05 22:30:58.501899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5df9d0368e07'
down_revision = '314c4ab28e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('company_info', table_name='company_profile')
    op.drop_table('company_profile')
    op.drop_index('email', table_name='signup')
    op.drop_index('password', table_name='signup')
    op.drop_table('signup')
    op.drop_index('email', table_name='login')
    op.drop_index('password', table_name='login')
    op.drop_table('login')
    op.drop_index('contact_info', table_name='user_profile')
    op.drop_table('user_profile')
    op.add_column('company', sa.Column('company_name', sa.String(length=120), nullable=False))
    op.alter_column('company', 'company_description',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_column('company', 're_password')
    op.add_column('user', sa.Column('contact_info', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_column('user', 're_password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('user', sa.Column('re_password', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'contact_info')
    op.add_column('company', sa.Column('re_password', mysql.VARCHAR(length=120), nullable=False))
    op.alter_column('company', 'company_description',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('company', 'company_name')
    op.create_table('user_profile',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('skills', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('contact_info', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_profile_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('contact_info', 'user_profile', ['contact_info'], unique=True)
    op.create_table('login',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('password', 'login', ['password'], unique=True)
    op.create_index('email', 'login', ['email'], unique=True)
    op.create_table('signup',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('password', 'signup', ['password'], unique=True)
    op.create_index('email', 'signup', ['email'], unique=True)
    op.create_table('company_profile',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('company_info', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='company_profile_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('company_info', 'company_profile', ['company_info'], unique=True)
    # ### end Alembic commands ###
