"""empty message

Revision ID: 7be72339c0e4
Revises: 5df9d0368e07
Create Date: 2020-02-05 23:23:53.522146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be72339c0e4'
down_revision = '5df9d0368e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=250), nullable=False),
    sa.Column('job_description', sa.String(length=500), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('job_date', sa.String(length=10), nullable=False),
    sa.Column('skills_needed', sa.String(length=500), nullable=False),
    sa.Column('hours_expected', sa.String(length=50), nullable=False),
    sa.Column('payment', sa.String(length=250), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hours_expected'),
    sa.UniqueConstraint('job_date'),
    sa.UniqueConstraint('job_description'),
    sa.UniqueConstraint('job_title'),
    sa.UniqueConstraint('payment'),
    sa.UniqueConstraint('skills_needed'),
    sa.UniqueConstraint('zip_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posting')
    # ### end Alembic commands ###
